swagger: '2.0'

info:
  version: '1'
  title: API
  description: A sample API

definitions:
  Subparts:
    type: object
    required:
      - subparts
    properties:
      subparts:
        type: array
        items:
          $ref: '#/definitions/Subpart'
  Subpart:
    type: object
    properties:
      name:
        type: string
      version:
        type: string
      spec_path:
        type: string

paths:
  /subparts:
    get:
      description: Get the available subparts
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Subparts'
